FROM scratch
MAINTAINER Ivan Porto Carrero <ivan@flanders.co.nz>

ADD ./ca-certificates.crt /etc/ssl/certs/ca-certificates.txt
ADD ./mime.types /etc/mime.types
#ADD https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types /etc/mime.types
